name: Docker Image CI for GHCR

on: 
  push

jobs:
  build_and_publish:
    runs-on: alpine-3.20.3
    steps:
      - uses: actions/checkout@v3
      - name: Pushes the image
        run: |
          docker login --username ModularMX --pasword ${{ secrets.GH_TOKEN }} ghcr.io
          docker build . --tag ghcr.io/ModularMX/openocd:12
          docker push ghcr.io/ModularMX/openocd:12
